# include "stdafx.h"
# include <iostream>
# include <string>
# include <stack>
using namespace std;
int var;
stack<int> int_stack;
stack<int*> pointer_stack;
int main() {
cout << " " << endl;
cout << "  This code illustrates basic arithmetic" << endl;
cout << "  and logical operations." << endl;
cout << " " << endl;
int_stack.push(var);
cout << " Variables are initialized to "zero"" << endl;
cout << " Value of var is:" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(5);
int_stack.push(4);
cout << " 5 - 4 = 1" << endl;
var = int_stack.top();
int_stack.pop();
int OVOAFXLBET = int_stack.top();
int_stack.pop();
int_stack.push(var + int OVOAFXLBET);
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(4);
int_stack.push(5);
cout << " 4 - 5 = -1" << endl;
int CRRGMAFHBC = int_stack.top();
int_stack.pop();
int HGQDIHLVYH = int_stack.top();
int_stack.pop();
int_stack.push(int CRRGMAFHBC + int HGQDIHLVYH);
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(5);
int_stack.push(4);
cout << " 5 div 4 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(4);
int_stack.push(5);
cout << " 4 div 5 = 4" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(4);
int_stack.push(3);
cout << " 4 / 3 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(3);
int_stack.push(4);
cout << " 3 / 4 = 0" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(0);
int_stack.push(1);
cout << " 0 & 1 = 0" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(0);
int_stack.push(1);
cout << " 0 | 1 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(0);
cout << " !0 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(4);
int_stack.push(3);
cout << " 4 <> 3 = 1 " << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(3);
int_stack.push(4);
cout << " 3 <= 4 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(3);
int_stack.push(4);
cout << " 3 >= 4 = 0" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(3);
int_stack.push(4);
cout << " 3 < 4 = 1" << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " --------------------------------" << endl;
int_stack.push(3);
int_stack.push(4);
cout << " 3 > 4 = 0 " << endl;
cout << int_stack.top() << endl;
int_stack.pop();
cout << " -------------------------------" << endl;
return 0;
}
